# Generated by Django 5.0.6 on 2024-06-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_priority_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_file/'),
        ),
    ]
