# Generated by Django 5.0.6 on 2024-06-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_taskinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinventory',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskinventory',
            name='created_at',
        ),
    ]
